### PR TITLE
Add new workflow section

### PR DESCRIPTION
**Pull request by mattdrayer**
@OpenLXP/contributors adding a new workflow section to the README file -- however I'm not done yet!

### CODE REVIEW

**Comment by mattdrayer** [comment]
@OpenLXP/contributors okay, this is ready for review!  Can I get two?

**Review by micson-us — APPROVED** [review]
Reviewed!

**Comment by mattdrayer** [comment]
Thanks!  Just need one more to merge!

**Review by KarenAJ — COMMENTED** [review]
Reviewed!

**Review by KarenAJ — APPROVED** [review]

**Pull request merged**
